### ISSUE TITLE
How create the pg_dump for python

### ISSUE THREAD

**Issue by AndresUrregoAngel** [jameshy/pgdump-aws-lambda#19]
There are any insights around how should I create the same bin for a python env? can I reuse the bin folder from here?

besides I got the error below upon execution:
```
{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is undefined or not exported",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is undefined or not exported",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
    "    at Module.load (internal/modules/cjs/loader.js:811:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)",
    "    at internal/main/run_main_module.js:17:11"
  ]
}
```

**Comment by jameshy** [comment]
Hi Andres!

Sure you can reuse the bin directory.

The error is because you are executing a nodejs Lambda function, which expects `index.handler` to be defined. For Python it is different, see https://docs.aws.amazon.com/lambda/latest/dg/python-programming-model-handler-types.html.

To make this project run as a python lambda, see these steps:
1. delete all javascript files
2. create python files with the same functionality
3. upload as a python lambda
